# Generated by Django 5.0.6 on 2026-05-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['name'], name='products_name_6f9890_idx'), models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'), models.Index(fields=['price'], name='products_price_fe467e_idx')],
            },
        ),
    ]
