from datetime import datetime
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .models import Order, OrderItem


@api_view(["POST"])
def create_order(request):
    """Create a new order"""
    try:
        payload = request.data
        
        # Create order (order_id will be auto-generated by the model)
        order = Order.objects.create(
            customer_name=payload.get("customer_name", ""),
            phone=payload.get("phone", ""),
            address=payload.get("address", ""),
            total=payload.get("total", 0),
            payment_method=payload.get("payment_method", "cod"),
            payment_status=payload.get("payment_status", "Pending COD"),
            status="Pending"
        )

        # Create order items from cart
        items = payload.get("items", [])
        for item in items:
            OrderItem.objects.create(
                order=order,
                product_id=item.get("id"),  # Cart item has 'id' for product_id
                product_name=item.get("name", ""),  # Cart item has 'name'
                quantity=item.get("qty", 1),  # Cart item has 'qty'
                price=item.get("price", 0)  # Cart item has 'price'
            )

        return Response({
            "id": order.id,  # This will be the generated order_id like "DP2505101234"
            "customer_name": order.customer_name,
            "total": order.total,
            "status": order.status,
            "message": "Order created successfully"
        }, status=status.HTTP_201_CREATED)

    except Exception as e:
        return Response(
            {"error": str(e)},
            status=status.HTTP_500_INTERNAL_SERVER_ERROR
        )


@api_view(["GET"])
def order_by_id(request, order_id):
    """Get order by ID with items"""
    try:
        order = Order.objects.filter(id=order_id).first()
        if not order:
            return Response(
                {"error": "Order not found"},
                status=status.HTTP_404_NOT_FOUND
            )

        # Get order items
        items = OrderItem.objects.filter(order=order).values(
            'id', 'product_id', 'product_name', 'quantity', 'price'
        )

        return Response({
            "id": order.id,
            "customer_name": order.customer_name,
            "phone": order.phone,
            "address": order.address,
            "total": order.total,
            "payment_method": order.payment_method,
            "payment_status": order.payment_status,
            "status": order.status,
            "items": list(items),
            "created_at": order.created_at,
            "updated_at": order.updated_at
        }, status=status.HTTP_200_OK)

    except Exception as e:
        return Response(
            {"error": str(e)},
            status=status.HTTP_500_INTERNAL_SERVER_ERROR
        )


@api_view(["GET"])
def get_all_orders(request):
    """Get all orders with pagination"""
    try:
        page = int(request.query_params.get("page", 1))
        limit = int(request.query_params.get("limit", 10))
        offset = (page - 1) * limit

        orders = Order.objects.all().order_by('-created_at')[offset:offset + limit]
        total = Order.objects.count()

        orders_list = []
        for order in orders:
            items_count = OrderItem.objects.filter(order=order).count()
            orders_list.append({
                "id": order.id,
                "customer_name": order.customer_name,
                "total": order.total,
                "status": order.status,
                "payment_status": order.payment_status,
                "items_count": items_count,
                "created_at": order.created_at
            })

        return Response({
            "orders": orders_list,
            "total": total,
            "page": page,
            "limit": limit
        }, status=status.HTTP_200_OK)

    except Exception as e:
        return Response(
            {"error": str(e)},
            status=status.HTTP_500_INTERNAL_SERVER_ERROR
        )


@api_view(["PUT"])
def update_order_status(request, order_id):
    """Update order status"""
    try:
        order = Order.objects.filter(id=order_id).first()
        if not order:
            return Response(
                {"error": "Order not found"},
                status=status.HTTP_404_NOT_FOUND
            )

        if "status" in request.data:
            order.status = request.data["status"]
        if "payment_status" in request.data:
            order.payment_status = request.data["payment_status"]

        order.save()
        return Response({
            "id": order.id,
            "status": order.status,
            "payment_status": order.payment_status,
            "message": "Order updated successfully"
        }, status=status.HTTP_200_OK)

    except Exception as e:
        return Response(
            {"error": str(e)},
            status=status.HTTP_500_INTERNAL_SERVER_ERROR
        )


@api_view(["DELETE"])
def cancel_order(request, order_id):
    """Cancel an order"""
    try:
        order = Order.objects.filter(id=order_id).first()
        if not order:
            return Response(
                {"error": "Order not found"},
                status=status.HTTP_404_NOT_FOUND
            )

        if order.status == "Delivered":
            return Response(
                {"error": "Cannot cancel a delivered order"},
                status=status.HTTP_400_BAD_REQUEST
            )

        order.status = "Cancelled"
        order.save()
        return Response(
            {"message": "Order cancelled successfully"},
            status=status.HTTP_200_OK
        )

    except Exception as e:
        return Response(
            {"error": str(e)},
            status=status.HTTP_500_INTERNAL_SERVER_ERROR
        )
